### ISSUE TITLE
assembly not signed

### ISSUE THREAD

**Issue by blorger** [dgg/testing-commons#3]
Assemblies in NUget packages don't provide strong name which makes them unusable in test assemblies with strong name.

**Comment by dgg** [comment]
You are totally correct.
I did not think there were that many people that still signed their assemblies that had the need for testing them, to be honest.

A quick workaround until I streamline the build process is to run the following command:

```
ildasm Testing.Commons.dll /out:Testing.Commons.il
ilasm Testing.Commons.il /dll /key=your.key.snk /output=Testing.Commons.signed.dll /quiet
```

or use something like [Assembly Strong Naming Toolkit](https://www.nuget.org/packages/Nivot.StrongNaming/) or [.NET Assembly Strong-Name Signer](https://www.nuget.org/packages/Brutal.Dev.StrongNameSigner/) or follow [these instructions](https://blog.maartenballiauw.be/post/2014/09/10/automatically-strong-name-signing-nuget-packages.html).

There is a catch, though, as I strongly believe against strong naming in NuGet packages (just Google around to find very opinionated people exposing their very argumented opinions) and people that require strong-naming are in minority.
That is why _Testing.Commons_ and their kin are not going to be strong-named by default, nor will be likely to get a strongly-named version of the assembly.
I will, however, make lives slightly easier to those that require strong naming assemblies.

I am not trying to convince you to ditch strong-naming as you surely have your reasons (and I hope they are beyond "is a company policy"), but if you have the chance, fight for it.

**Comment by dgg** [comment]
I commented on making lives easier to those that have to put up with strong-naming.

That is no longer the case as the workaround stated [here](https://github.com/dgg/testing-commons/wiki/Developers#strong-naming) is more than good enough.
